### ISSUE TITLE
Не стабильный размер Рэнж бара

### ISSUE THREAD

**Issue by OlegT911** [SBProX/Test-Flight#17]
При заданном значении Рэнж 10,  должно быть 11 кластеров, но их количество постоянно самопроизвольно меняется.
![25-10-2021, 20'42'08](https://user-images.githubusercontent.com/60439200/138745540-7cc75fbe-dd0e-4763-bbe0-490f3a80a8bb.png)

**Comment by alfovit** [comment]
> При заданном значении Рэнж 10, должно быть 11 кластеров,

Почему это должно быть 11 кластеров??? Посмотрите в https://ru.tradingview.com/, там при ренж 10 все бары 10.

**Comment by OlegT911** [comment]
> > При заданном значении Рэнж 10, должно быть 11 кластеров,
> 
> Почему это должно быть 11 кластеров??? Посмотрите в https://ru.tradingview.com/, там при ренж 10 все бары 10.
> 
> В Атасе только что проверил, тоже 10 !!!

Потому что, в Атас, Нинзя, Тигра, Кускальп -11

![21-11-2021, 00'22'27](https://user-images.githubusercontent.com/60439200/142741321-05fb9546-7aba-4444-a178-df25b18753a4.png)
