### ISSUE TITLE
Не верно масштабируются фигуры Clouds в зависимости от объема

### ISSUE THREAD

**Issue by ilexush** [SBProX/Test-Flight#43]
Больший объем рисует меньший квадрат и наоборот.
Настройки прикладываю в виде скриншот
![Ошибка](https://user-images.githubusercontent.com/68943957/139632431-88e28ba1-de6c-4c94-a5e0-1f866a2d709a.jpg)
а
![Настройки](https://user-images.githubusercontent.com/68943957/139632434-60093ba0-9231-4bba-98b2-83b282664f4b.jpg)
.

**Comment by SBProX** [comment]
Это не ошибка.

У вас стоит перевес bid-ask - размера фигуры считается в данном случае по перевесу, а не по объему.
