### ISSUE TITLE
Долгая загрузка и перерисовка инструмента на разных таймингах - как ускорить процедуру в сотни раз!!!

### ISSUE THREAD

**Issue by Arseniy-Omsk** [SBProX/Test-Flight#56]
Что не нравилось в SBpro 6 и перекочевало в SBpro 7, то что нет быстрой перерисовки графика при переходе на другой тайминг.
(Скажу сразу, что работаю с барами без кластерных графиков. Мне нужны в основном для работы с графиками индикаторы вертикальных объёмов. дельты и горизонтальных объёмов, дополнительно скользящие средние. Таких пользователей думаю много, это те кто занимаются VSA анализом или по методу Пурнова побарным анализом, так же те кто дополняет систему тех анализа дельтой и горизонтальными объёмами.)
Такие программы как Транзак и Квик перерисовывают график с одного тайминга на другой с задержкой несколько секунд (бары, свечи), что позволяет переключаться на лету и не держать несколько графиков одновременно. 
Хотя это по сути не лишнее - одновременно контролировать несколько окон. Но когда требуется лишь изредка проконтролировать мелкий таймфрейм - перейти с часа на минутку или 10-ти минутку то для SBpro это была всегда проблема - сам процесс начинается с загрузки с сервера, потом  кэширование и только после этого отрисовка на экране. Т.е. то же время что и новая загрузка с параметрами нового графика.
Это очень долго.
Предлагаю реализовать быструю или ускоренную перерисовку (опять же только для свечных и барных графиков, для тех кто пользуется кластерными это может быть не актуально, но побарникам и свечникам очень актуально, просто жизненно необходимо!!!). Во первых - не нужно начинать перерисовывать весь график с самого начала, надо реализовать перерисовку с конца - той части которая находится в экране и расширив границы к примеру на несколько дней (10 дней вполне хватит) в стороны для минутного или часового если переход идет с дневного таймфрейма. И цель - мгновенно начать перерисовывать график в окне.
Так же расположить кнопки тайминга не на выпадающим меню, а горизонтально, как в XTick, так будет удобнее. Хотя это только для удобства но не главное - главное это скорость отрисовки.
Немного понимаю как работают программы и понимаю что каждый график это таблица на диске или в оперативной памяти. Поэтому думаю что подгружать с сервера надо всегда одну таблицу - минутную, и к примеру писать её на диск в папку инструмента. Из этой исходной таблицы и делать преобразования (создавать новые таблицы под каждый тайминг и писать отдельными файлами в папку инструмента). И преобразования тоже сохранять на диск. И дописывать недостающие пробелы при повторных обращениях будет быстрее и обработка будет занимать меньше времени.
Т.е. первое обращение к новому таймингу порождает создание новой долговременной таблицы на диске и отрисовку на экране. Повторное обращение к тому же таймингу инициирует загрузку ранее созданной долговременной таблицы и создание её недостающей части и прежде всего начиная с последних минут.
Опять же - не с начала и до конца - а с конца и до начала. Это правильнее. И сначала - первые 10 дней (несколько экранов) и вывод на экран, а потом остальное в фоновом режиме.
Когда двигаешь таблицу в том же Квике - она подгружается от курсора.
Это правильно. Сжимаешь - тоже самое. Так как перерисовывается экран надо делать логику загрузки всех окон и таблиц и их пересчет.
К примеру при запуске программы не появляется окно о загрузке графиков, а начинается экстренное подкачивание с конца в таблицу которая сохранена на диске с предыдущей сессии и экстренная загрузка графики для отрисовки графика на экран - кэширование и отрисовка на экране начиная с последнего бара. И отрисовку нужно начинать немедленно после прогрузки кэша для экрана - бар за баром и свечу за свечей. И в фоновом режиме продолжать кэширование более ранних данных.
Сейчас это наоборот - сначала идет загрузка с самого начала периода, потом кэширование с самого начала периода и отрисовка задерживается на время всех этих действий. Что увеличивает время начала работы с графиком многократно.
К примеру, самый распространенный случай - у меня открыт часовик на последнем дне, график начинается с начала года. Реально мне надо после включения программы увидеть что происходит сейчас - сегодня. И график нескольких предыдущих дней. Программа же пока не скачает и не загрузит весь график не показывает мне его, хоть те данные мне сейчас не нужны. Они нужны иногда - когда я сжимаю график или перемещаюсь в какой то его более ранний период.
Для всех таймингов кроме дневных и начиная с 4-х часовых можно минимизировать время загрузки графика если сразу кэшировать последние 10 рабочих дней, а остальную часть кэшировать в фоновом режиме после отрисовки на экране требуемой области (обычно это конец графика - последний день и последняя цена и ширина окна).
Так несколько десятков окон будут перерисовываться в сотни раз быстрее. И если кэшировать тайминги то и столько окон будет не нужно - вместо 4-х окон на один инструмент  - на каждый тайминг по окну - дневку, часовик, М10 и М1. Останется одно окно с одним инструментом - максимум два окна.
Плюс если так же быстро будут перерисовываться тайминги таблиц - в фоновом режиме можно их заполнять.
Т.е. если к примеру на инструменте был открыт тайминг М10, Н1 и Д1, и соответственно эти таблицы были созданы, то имеет смысл в фоновом режиме их дописывать и даже кешировать, так как велика вероятность что пользователь будет к ним снова обращаться. Не создавая новые окна - а одно окно с инструментом - несколько таблиц на разных таймингах кэшируются.
Можно к примеру дать возможность самому пользователю отметить автоматическое кэширование каких таймингов ему нужно - не для каждого инструмента в отдельности, а в принципе. Чтобы если он открывает новый инструмент загружался график в первую очередь того тайминга который он открывает, но в фоновом режиме уже идет кэширование по рабочим для пользователя таймингам.
Конечно возникнут сложности с настройкой индикаторов - к примеру скользящие на один тайминг будут иметь другое значение для другого тайминга и при переключении искажаться. Но это надо думаю реализовывать как подстройку к каждому таймингу или задавать параметры для индикаторов в одном тайминге, чтобы он по нему отрисовывался во всех других, на которые идет переключение. Но это наверное единственные индикаторы для которых важен тайминг. Тот же АТР как раз не требует подстройки.

**Comment by SBProX** [comment]
Внимательно прочитали ваш тикет.

То что вы описали, невероятно сложная система с кучей потенциальных багов.
Вы даже себе не представляете насколько сложно это все реализуется.

Во-первых, сейчас данные кешируются один раз - да, в первый раз нужно подождать.
Но потом будет быстро.

При переключении ТФ сделать моментальную смену графика не представляется возможным, так как SBPro это не Quik и не MT. В барах хранится большое кол-во информации, и это информация просчитывается только когда вы нажимаете Apply. 

Мы не можем храниться ВСЮ информацию по ВСЕМ тайм-фреймам в оперативной памяти для быстрого переключения. Это крайне сложно, и не понятно зачем.

**Comment by Arseniy-Omsk** [comment]
Спасибо что внимательно прочитали!
Давайте упростим задачу - отрисовка баров **окна** и далее подгрузка в фоне. В Квике и транзаке загрузка программы первоначально идет тоже не секунды, можно сказать сравнима по времени.  Возможно Вы правы что это надо сделать один раз и это не проблема. 
Но потом переключение таймфрейма занимает секунды.
А сейчас приходится держать в SBpro **по графику на каждый таймфрейм**.
Вот количество графиков сразу увеличивается. Дневной - обязательно, час - тоже, 10 или 5 минут, и минутный.
А если надо несколько инструментов отслеживать?
И на Квике или Транзаке если загрузка графика занимает время, то переключение между таймфреймами несколько секунд.
А Вы пишете что это принципиально неразрешимая задача. Странно всё это.
